### ISSUE TITLE
[Windows] jMonkeyBuilder 1.6.1

### ISSUE THREAD

**Issue by demkom58** [JavaSaBr/IntelliJ-jME-Plugin#2]
When I specify the path to jMonkeyBuilder.exe and apply it.
IDEA writes that it does not support this version of jMonkeyBuilder.

**Comment by JavaSaBr** [comment]
Could you recheck it on 1.3.1 version of the plugin, please?

**Comment by demkom58** [comment]
![image](https://user-images.githubusercontent.com/5957073/36514375-c953231a-177c-11e8-80f2-7d8329fb0cd1.png)
![image](https://user-images.githubusercontent.com/5957073/36514202-0a613a3c-177c-11e8-8403-85a9f1116ed1.png)

I also noticed that the jMonkeyBuilder does not start. I have tried to run jar, that's the error I got.
[error.txt](https://github.com/JavaSaBr/IntelliJ-jME-Plugin/files/1746285/error.txt)

**Comment by JavaSaBr** [comment]
about the second problem, jMB still doesn't support java 9.

**Comment by demkom58** [comment]
Thanks, now the jar is launched without errors.
But jMonkeyBuilder.exe still does not start.

**Comment by JavaSaBr** [comment]
> But jMonkeyBuilder.exe still does not start.
did you try to launch the .exe file from terminal?

**Comment by demkom58** [comment]
![image](https://user-images.githubusercontent.com/5957073/36587428-d4e25608-188d-11e8-9082-0ca0f0162aa4.png)

**Comment by JavaSaBr** [comment]
Do you have any log there:
%userhome%/.jmonkeybuilder/log/
?

**Comment by demkom58** [comment]
That folder is empty.
Logs are created only when I run the .jar file.

**Comment by JavaSaBr** [comment]
I have no ideas else... I will recheck it on my virtual windows machine again. Could you check the last verison 1.7.2, please?

**Comment by demkom58** [comment]
The same situation with the new version.

**Comment by JavaSaBr** [comment]
@demkom58 is your OS x64?

**Comment by demkom58** [comment]
yes

**Comment by JavaSaBr** [comment]
so, you can use the jar version of jMB from intellij plugin... If I find what it can be I will let you know about this.

**Comment by demkom58** [comment]
![image](https://user-images.githubusercontent.com/5957073/36593705-8a26b31e-18a3-11e8-9e76-6f6e294d45c4.png)
IDEA does not show .jar files.

**Comment by JavaSaBr** [comment]
Did you try to put the path manually to the text field?

**Comment by demkom58** [comment]
![image](https://user-images.githubusercontent.com/5957073/36593841-25d0fdba-18a4-11e8-87f8-5863aad9866d.png)

**Comment by JavaSaBr** [comment]
ok, I will check it as well.

**Comment by JavaSaBr** [comment]
I can reproduce your problem with launching jMB from exe file :( 
https://imgur.com/01MaZmb
I will update the IntelliJ plugin to support launch the .jar file.

**Comment by JavaSaBr** [comment]
Could you try to launch a .jar version of jMB from IDEA using this version of the plugin, please?
https://yadi.sk/d/kcM-E9x-3SmTXf

**Comment by demkom58** [comment]
![image](https://user-images.githubusercontent.com/5957073/36693626-8c44f900-1b44-11e8-9fd1-ddf069164b04.png)

**Comment by demkom58** [comment]
Now it starts and works, but an exception is thrown.

![image](https://user-images.githubusercontent.com/5957073/36696256-5cd20c00-1b4c-11e8-8062-a36c12bb10b8.png)

https://pastebin.com/xpaqTCUj

**Comment by JavaSaBr** [comment]
@demkom58 hm, it's interesting... I will look at it later.

**Comment by JavaSaBr** [comment]
@demkom58 could you delete old versions of the library here and recheck the problem?
https://imgur.com/IOjixQl

**Comment by demkom58** [comment]
`class with name 'com.ss.jme.plugin.ui.action.OpenInJmbAction' cannot be loaded [Plugin: com.ss.jme.plugin]
com.intellij.diagnostic.PluginException: class with name 'com.ss.jme.plugin.ui.action.OpenInJmbAction' cannot be loaded [Plugin: com.ss.jme.plugin]
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:194)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:159)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:486)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:474)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.unStub(DefaultActionGroup.java:358)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.getChildren(DefaultActionGroup.java:316)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:188)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:153)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:227)
	at com.intellij.openapi.actionSystem.impl.Utils.fillMenu(Utils.java:363)
	at com.intellij.openapi.actionSystem.impl.ActionPopupMenuImpl$MyMenu.show(ActionPopupMenuImpl.java:107)
	at com.intellij.ui.PopupHandler$2.invokePopup(PopupHandler.java:87)
	at com.intellij.ui.PopupHandler.mouseReleased(PopupHandler.java:58)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6541)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at com.intellij.ui.treeStructure.Tree.processMouseEvent(Tree.java:423)
	at com.intellij.ide.dnd.aware.DnDAwareTree.processMouseEvent(DnDAwareTree.java:58)
	at java.awt.Component.processEvent(Component.java:6306)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4897)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.j(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:646)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NoClassDefFoundError: com/ss/rlib/network/packet/impl/AbstractWritablePacket
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:276)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:272)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:241)
	at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:142)
	at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:74)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:61)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:152)
	... 49 more
Caused by: java.lang.ClassNotFoundException: com.ss.rlib.network.packet.impl.AbstractWritablePacket PluginClassLoader[com.ss.jme.plugin, 1.3.2] com.intellij.ide.plugins.cl.PluginClassLoader@777ecd9b
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:63)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 62 more`

**Comment by demkom58** [comment]
![image](https://user-images.githubusercontent.com/5957073/36939612-79c05602-1f3c-11e8-91d7-1c546faf38ce.png)

![image](https://user-images.githubusercontent.com/5957073/36939615-84ead962-1f3c-11e8-8eb1-39b5859df80a.png)

![image](https://user-images.githubusercontent.com/5957073/36939624-b708201c-1f3c-11e8-8746-bf94d1209288.png)

# Randomly can show such a window.
![image](https://user-images.githubusercontent.com/5957073/36939618-8e4a1e8c-1f3c-11e8-8176-739e289c15e9.png)
When this window appears, the application does not start.

**Comment by JavaSaBr** [comment]
@demkom58 did you remove all libraries? :)

**Comment by demkom58** [comment]
I apologize, I was sure that I deleted it.
Now everything works perfectly! : D

**Comment by JavaSaBr** [comment]
@demkom58 haha, ok :)
